// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<mysticalagriculture:diamond_seeds>);
recipes.remove(<mysticalagriculture:diamond_seeds>);
recipes.remove(<mysticalagriculture:diamond_seeds>);
recipes.remove(<mysticalagriculture:gold_seeds>);
recipes.remove(<mysticalagriculture:gold_seeds>);
recipes.remove(<mysticalagriculture:gold_seeds>);
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<cyclicmagic:glowing_chorus>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<powersuits:powerarmorcomponent:4>);
recipes.remove(<techreborn:grinder>);
recipes.remove(<actuallyadditions:block_grinder>);
recipes.remove(<actuallyadditions:block_grinder>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<dungeontactics:iron_ring>);
recipes.remove(<inventorypets:nugget_coal>);
recipes.remove(<jaopca:item_nuggetcoal>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<akashictome:tome>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<portalgun:item_portalgun>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<mekanism:salt>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:tinkertable>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:powerarmor_torso>);
recipes.remove(<powersuits:power_fist>);
recipes.remove(<powersuits:power_fist>);

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<jaopca:item_nuggetcoal> * 9, [<minecraft:coal>]);
recipes.removeShapeless(<inventorypets:nugget_coal> * 8, [<minecraft:coal>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<extrautils2:angelring:5>, [[<mod_lavacow:undyingheart>, <extrautils2:angelring>]]);
recipes.removeShaped(<extrautils2:angelring:3>, [[<ore:ingotDemonicMetal>, <extrautils2:angelring>]]);

recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.removeShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<inventorypets:nugget_coal> * 8, [<immersiveengineering:tool>, <ore:itemCoal>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<chancecubes:chance_cube>, [[<ore:blockLapis>, <minecraft:lapis_block>, <minecraft:lapis_block>], [<minecraft:lapis_block>, <ore:netherStar>, <ore:blockLapis>], [<minecraft:lapis_block>, <minecraft:lapis_block>, <ore:blockLapis>]]);
recipes.addShaped(<extrautils2:angelring:4>, [[<extrautils2:angelblock>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:1>, [[<mekanism:crystal:2>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:3>, [[<extrautils2:ingredients:11>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:2>, [[<harvestcraft:fairybreaditem>, <extrautils2:angelring>]]);
recipes.addShaped(<randomthings:ingredient:5>, [[<ore:dustGlowstone>, <minecraft:red_mushroom>]]);
recipes.addShaped(<harvestcraft:toastitem>, [[<ore:cropCinnamon>, <dungeontactics:toast>]]);
recipes.addShaped(<extrautils2:angelring:2>, [[<harvestcraft:fairybreaditem>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:2>, [[<harvestcraft:fairybreaditem>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:4>, [[<extrautils2:angelblock>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:3>, [[<extrautils2:ingredients:11>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring:5>, [[<midnight:nagrilite_ingot>, <extrautils2:angelring>]]);
recipes.addShaped(<extrautils2:angelring>, [[<mekanism:crystal:1>, <mekanism:crystal:2>, <mekanism:crystal:1>], [<twilightforest:trophy:5>, <tconstruct:materials:50>, <thebetweenlands:ring_of_dispersion>], [<mekanism:crystal:1>, <simplyjetpacks:metaitemmods:29>, <mekanism:crystal:1>]]);
recipes.addShaped(<extrautils2:angelring>, [[<mekanism:crystal:1>, <mekanism:crystal:2>, <mekanism:crystal:1>], [<twilightforest:trophy:5>, <tconstruct:materials:50>, <thebetweenlands:ring_of_dispersion>], [<mekanism:crystal:1>, <simplyjetpacks:metaitemmods:29>, <mekanism:crystal:1>]]);
recipes.addShaped(<powersuits:powerarmorcomponent:4>, [[<jaopca:item_platedenseiridium>, <thermalfoundation:material:326>, <jaopca:item_platedenseiridium>], [<powersuits:powerarmorcomponent:12>, <powersuits:powerarmorcomponent:8>, <powersuits:powerarmorcomponent:12>], [<ore:plateDenseIridium>, <ore:platePlatinum>, <ore:plateDenseIridium>]]);
recipes.addShaped(<dungeontactics:iron_ring>, [[<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>], [<minecraft:iron_nugget>, null, <ore:nuggetIron>], [<ore:nuggetIron>, <ore:nuggetIron>, <ore:nuggetIron>]]);
recipes.addShaped(<powersuits:tinkertable>, [[<ore:ingotKnightmetal>, <rats:arcane_technology>, <ore:ingotKnightmetal>], [<enderio:item_alloy_ingot>, <twilightforest:knightmetal_ingot>, <ore:ingotElectricalSteel>], [<ore:ingotElectricalSteel>, <ore:ingotKnightmetal>, <ore:ingotElectricalSteel>]]);
//recipes.addShaped(<mystcraft:writingdesk>, [[null, <minecraft:carpet:14>, null], [<minecraft:bookshelf>, <ore:netherStar>, <minecraft:bookshelf>], [<ore:bookshelf>, <minecraft:log>, <ore:bookshelf>]]);
recipes.addShaped(<techreborn:chunk_loader>, [[<techreborn:part:5>, <ore:enderpearl>, <techreborn:part:5>], [<mekanism:ingot>, <techreborn:part:41>, <ore:ingotRefinedObsidian>], [<ore:lapotronCrystal>, <techreborn:plates:32>, <ore:lapotronCrystal>]]);
//recipes.addShaped(<mystcraft:blockinkmixer>, [[<minecraft:carpet:15>, null, null], [<minecraft:stone>, <minecraft:nether_star>, <minecraft:stone>], [<minecraft:stone>, null, <minecraft:stone>]]);
//recipes.addShaped(<mystcraft:writingdesk>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <minecraft:dragon_egg>, <ore:plankWood>]]);
//recipes.addShaped(<techreborn:ingot:14>;
recipes.addShaped(<akashictome:tome>, [[<minecraft:stick>]]);
recipes.addShaped(<portalgun:item_portalgun>, [[<actuallyadditions:block_crystal_empowered:2>, <extrautils2:ingredients:17>, <extrautils2:ingredients:17>], [<techreborn:part:3>, <portalgun:item_miniature_black_hole>, <extrautils2:ingredients:17>], [<extrautils2:ingredients:17>, <actuallyadditions:block_crystal_empowered:2>, <industrialforegoing:pink_slime_ingot>]]);
recipes.addShaped(<powersuits:tinkertable>, [[<ore:plateEmerald>, <rats:arcane_technology>, <ore:plateEmerald>], [<ore:ingotSteel>, <ore:skullZombieElectrode>, <ore:ingotSteel>], [<ore:ingotSteel>, <enderio:item_material:20>, <thermalfoundation:material:160>]]);
recipes.addShaped(<powersuits:powerarmor_torso>, [[<techreborn:plates:36>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <mekanismtools:osmiumchestplate>, <techreborn:plates:38>], [<techreborn:plates:36>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.addShaped(<powersuits:powerarmor_torso>, [[<ore:plateadvancedAlloy>, null, <techreborn:plates:36>], [<techreborn:plates:38>, <conarm:chest_core>, <techreborn:plates:38>], [<ore:plateadvancedAlloy>, <techreborn:part:43>, <techreborn:plates:36>]]);
recipes.addShaped(<powersuits:power_fist>, [[<ore:ingotEndSteel>, <openmodularturrets:intermediate_tiered:9>, <enderio:item_alloy_ingot:8>], [null, <techreborn:advanceddrill>, null], [null, <ore:ingotVibrantAlloy>, null]]);
recipes.addShaped(<thermalfoundation:material:160>, [[<ore:dustObsidian>, <ore:dustCoal>, <ore:dustObsidian>], [<ore:dustCoal>, <ore:ingotBrass>, <ore:dustCoal>], [<ore:dustObsidian>, <ore:dustCoal>, <thermalfoundation:material:770>]]);

